apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
spec:
  # storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dependencies
spec:
  # storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
