spring:
  application:
    name: data-anon
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

    # session_replication_role=replica disables triggers/fk checks/etc for this session, speeding
    # things and preventing some modules from attempting to update modification timestamps/etc
    jdbcUrl: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}?options=-c%20session_replication_role=replica&ApplicationName=folio-data-anonymization

    # these should be kept in line with the number of threads (JobConfig) and
    # the maximum amount of time we're currently blocking for DB queries (JooqConfig)
    minimum-idle: 5
    maximum-pool-size: 100
    connection-timeout: 120000 # two minutes in MS

  keycloak-datasource:
    username: ${KC_USERNAME:${DB_USERNAME:postgres}}
    password: ${KC_PASSWORD:${DB_PASSWORD:postgres}}

    jdbcUrl: jdbc:postgresql://${KC_HOST:${DB_HOST:postgres}}:${KC_PORT:${DB_PORT:5432}}/${KC_DATABASE:keycloak}?options=-c%20session_replication_role=replica&ApplicationName=folio-data-anonymization-keycloak

    # these should be kept in line with the number of threads (JobConfig) and
    # the maximum amount of time we're currently blocking for DB queries (JooqConfig)
    minimum-idle: 5
    maximum-pool-size: 100
    connection-timeout: 120000 # two minutes in MS

  sql:
    init:
      # to boot up application despite any DB connection issues
      continue-on-error: false
