# github action workflow to run black formatter check and linting checks for our python code

name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install data anonymizer + dependencies via poetry
        run: |
          pip install -r requirements.txt
          poetry install
      - name: Lint with flake8
        run: poetry run flake8
      - name: Format with black
        run: poetry run black --check --diff .