name: Maven central workflow

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maven:
    uses: folio-org/.github/.github/workflows/maven.yml@8b59acede585b74b1b717fa59a6539c5852d4278 # v1
    # Only handle push events from the main branch or tags, to decrease PR noise
    if: github.ref_name == github.event.repository.default_branch ||
      github.event_name != 'push' || github.ref_type == 'tag' || github.actor == 'renovate[bot]'
    secrets: inherit # NOSONAR
    with:
      publish-module-descriptor: false
      do-docker: false
      do-sonar-scan: false # done at PR level
      do-maven-deploy: false # done below

  print:
    name: print
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          echo "github.ref_name=${{github.ref_name}}"
          echo "github.ref_type=${{github.ref_type}}"

  run:
    name: Deploy to GitHub Packages
    if: ${{ github.ref_name == github.event.repository.default_branch || github.ref_type == 'tag' }}
    needs: maven
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup Java for Nexus
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        with:
          java-version: 21
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set maven and code version to tag (tag only)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          sed -i "s/@placeholder@/${{ github.ref_name }}/g" src/main/java/org/folio/anonymization/config/Version.java
          mvn --batch-mode versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false

      - name: Set code version to commit hash (non-tag only)
        if: ${{ github.ref_type != 'tag' }}
        run: sed -i "s/@placeholder@/${{ github.sha }}/g" src/main/java/org/folio/anonymization/config/Version.java

      - name: Deploy to Nexus
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
