name: Maven central workflow

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maven:
    uses: folio-org/.github/.github/workflows/maven.yml@e4284b09dd90107636f754f5eca860cfc79f0655 # v1
    # Only handle push events from the main branch or tags, to decrease PR noise
    if: github.ref_name == github.event.repository.default_branch ||
      github.event_name != 'push' || github.ref_type == 'tag' || github.actor == 'renovate[bot]'
    secrets: inherit # NOSONAR
    with:
      publish-module-descriptor: false
      do-docker: false
      do-sonar-scan: false # done at PR level
      do-maven-deploy: false # done below

  run:
    name: Deploy to GitHub Packages
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    needs: maven
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup Java for Nexus
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: 21
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Deploy to Nexus
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
