# github action workflow to run tests for folio data anonymization

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install data anonymizer + dependencies via poetry
        run: |
          pip install -r requirements.txt
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest -rP
