name: Type Checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install data anonymizer + dependencies via poetry
        run: |
          pip install -r requirements.txt
          poetry install
      - name: Type checking with mypy
        run: poetry run mypy folio_data_anonymization tests